### ISSUE TITLE
remeshing while keep pre-defined vertex set

### ISSUE THREAD

**Issue by maolingao** [sgsellan/botsch-kobbelt-remesher-libigl#7]
Hi Silvia,

finally I've looked into the `decimate` function in libigl to remesh a high resolution mesh while preserving a given set of vertices. However after reading into it (https://github.com/libigl/libigl/blob/main/include/igl/decimate.h), it sounds to me that the lambda `cost_and_placement` is defined per edge, rather per vertex as wished. Thus it doesn't offer a direct control over the to-be-preserved vertices. 

Alternatively, the function `remeshmesh_mex(V,F,h,iterations,fixed_indeces)` seems to do the job, with `fixed_indeces` defines the vertex set to keep.  Will the implementation be wrapped up any time soon?

many thanks in advance,
Maolin

**Comment by sgsellan** [comment]
Hi Maolin!

My remesher simply uses libigl's `decimate` function giving infinite cost to any edge containing a fixed vertex; nothing smarter than that, so you could get the same functionality using `decimate`. The _proper_ way of doing this, which is not implemented in this code, would be to allow collapsing of edges only along the feature direction, as described in "A Remeshing Approach to Multiresolution Modeling". I plan on implementing this proper way of doing things in the future, but I don't know when since I am quite busy right now :)
